VW.MSU.UI/Models/ErrorViewModel.cs
using System;

namespace VW.MSU.UI.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

VW.MSU.UI/Models/InputModel.cs
namespace VW.MSU.UI.Models
{
    public class InputModel
    {
        public string Data { get; set; }
    }
}

VW.MSU.UI/Models/NotificationSettings.cs
namespace VW.MSU.UI.Models
{
    public class NotificationSettings
    {
        public string RequestUrl { get; set; }
        public string ApiKey { get; set; }
        public string SenderId { get; set; }
        public string Priority { get; set; }
    }
}

VW.MSU.UI/Models/SFDCSettings.cs
namespace VW.MSU.UI.Models
{
    public class SFDCSettings
    {
        public string LoginUrl { get; set; }
        public string VinDataUrl { get; set; }
    }
}

VW.MSU.UI/Models/SMTPSettings.cs
namespace VW.MSU.UI.Models
{
    public class SMTPSettings
    {
        public string Host { get; set; }
        public int Port { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string FromAddress { get; set; }
        public string FromName { get; set; }
        public bool EnableSsl { get; set; }
    }
}

VW.MSU.UI/Controllers/ModelsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using VW.MSU.Common;
using VW.MSU.Data.Models;
using VW.MSU.Models;
using VW.MSU.Services;
using VW.MSU.UI.Models;

namespace VW.MSU.UI.Controllers
{
    [Authorize]
    [SessionExpire]
    public class ModelsController : BaseController
    {
        public readonly ILogger<ModelsController> _logger;

        public ModelsController(IWebHostEnvironment hostingEnvironment, ILogger<ModelsController> logger, IConfiguration config, VWContext vwContext, IOptions<SFDCSettings> sfdcSettings)
            : base(hostingEnvironment, config, vwContext, sfdcSettings.Value)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            List<ModelsModel> model;

            model = _vwContext.Models.Where(x => !x.IsDeleted).Select(x => new ModelsModel
            {
                Id = x.Id,
                Name = x.Name
            }).OrderBy(x => x.Name).ToList();

            return View(model);
        }

        public IActionResult CreateOrUpdate(int id)
        {
            ModelsModel modelsModel = new ModelsModel();
            Data.Models.Models model = null;

            if (id > 0)
                model = _vwContext.Models.Where(x => x.Id == id).FirstOrDefault();

            if (model != null)
            {
                modelsModel = new ModelsModel()
                {
                    Id = model.Id,
                    Name = model.Name,
                    Image = model.Image,
                    FrontAngleImage = model.FrontAngleImage,
                    BackAngleImage = model.BackAngleImage,
                    RightAngleImage = model.RightAngleImage,
                    LeftAngleImage = model.LeftAngleImage
                };
            }

            return View(modelsModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreateOrUpdate(ModelsModel modelsModel)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    Data.Models.Models model = null;
                    if (modelsModel.Id > 0)
                    {
                        model = _vwContext.Models.Where(x => x.Id == modelsModel.Id).FirstOrDefault();
                    }
                    else
                    {
                        model = new Data.Models.Models
                        {
                            IsDeleted = false
                        };
                    }

                    model.Name = modelsModel.Name;

                    if (modelsModel.Id > 0)
                    {
                        _vwContext.Models.Update(model);
                    }
                    else
                    {
                        _vwContext.Models.Add(model);
                    }

                    _vwContext.SaveChanges();

                    if (modelsModel.ImageBlob != null && modelsModel.ImageBlob.Length > 0)
                    {
                        var assetPath = $"{_hostingEnvironment.WebRootPath}/Content/Models/{model.Id}";
                        var uploadFile = string.Empty;

                        using (var ms = new MemoryStream())
                        {
                            modelsModel.ImageBlob.CopyTo(ms);
                            var fileBytes = ms.ToArray();
                            uploadFile = Convert.ToBase64String(fileBytes);
                        }

                        UtilityServices.UploadBase64String(assetPath, $"{model.Id}{Path.GetExtension(modelsModel.ImageBlob.FileName)}", uploadFile);
                        model.Image = $"/Content/Models/{model.Id}/{model.Id}{Path.GetExtension(modelsModel.ImageBlob.FileName)}";
                    }

                    if (modelsModel.FrontAngleImageBlob != null && modelsModel.FrontAngleImageBlob.Length > 0)
                    {
                        var assetPath = $"{_hostingEnvironment.WebRootPath}/Content/Models/{model.Id}";
                        var uploadFile = string.Empty;

                        using (var ms = new MemoryStream())
                        {
                            modelsModel.FrontAngleImageBlob.CopyTo(ms);
                            var fileBytes = ms.ToArray();
                            uploadFile = Convert.ToBase64String(fileBytes);
                        }

                        UtilityServices.UploadBase64String(assetPath, $"{model.Id}_Front{Path.GetExtension(modelsModel.FrontAngleImageBlob.FileName)}", uploadFile);
                        model.FrontAngleImage = $"/Content/Models/{model.Id}/{model.Id}_Front{Path.GetExtension(modelsModel.FrontAngleImageBlob.FileName)}";
                    }

                    if (modelsModel.BackAngleImageBlob != null && modelsModel.BackAngleImageBlob.Length > 0)
                    {
                        var assetPath = $"{_hostingEnvironment.WebRootPath}/Content/Models/{model.Id}";
                        var uploadFile = string.Empty;

                        using (var ms = new MemoryStream())
                        {
                            modelsModel.BackAngleImageBlob.CopyTo(ms);
                            var fileBytes = ms.ToArray();
                            uploadFile = Convert.ToBase64String(fileBytes);
                        }

                        UtilityServices.UploadBase64String(assetPath, $"{model.Id}_Back{Path.GetExtension(modelsModel.BackAngleImageBlob.FileName)}", uploadFile);
                        model.BackAngleImage = $"/Content/Models/{model.Id}/{model.Id}_Back{Path.GetExtension(modelsModel.BackAngleImageBlob.FileName)}";
                    }

                    if (modelsModel.LeftAngleImageBlob != null && modelsModel.LeftAngleImageBlob.Length > 0)
                    {
                        var assetPath = $"{_hostingEnvironment.WebRootPath}/Content/Models/{model.Id}";
                        var uploadFile = string.Empty;

                        using (var ms = new MemoryStream())
                        {
                            modelsModel.LeftAngleImageBlob.CopyTo(ms);
                            var fileBytes = ms.ToArray();
                            uploadFile = Convert.ToBase64String(fileBytes);
                        }

                        UtilityServices.UploadBase64String(assetPath, $"{model.Id}_Left{Path.GetExtension(modelsModel.LeftAngleImageBlob.FileName)}", uploadFile);
                        model.LeftAngleImage = $"/Content/Models/{model.Id}/{model.Id}_Left{Path.GetExtension(modelsModel.LeftAngleImageBlob.FileName)}";
                    }

                    if (modelsModel.RightAngleImageBlob != null && modelsModel.RightAngleImageBlob.Length > 0)
                    {
                        var assetPath = $"{_hostingEnvironment.WebRootPath}/Content/Models/{model.Id}";
                        var uploadFile = string.Empty;

                        using (var ms = new MemoryStream())
                        {
                            modelsModel.RightAngleImageBlob.CopyTo(ms);
                            var fileBytes = ms.ToArray();
                            uploadFile = Convert.ToBase64String(fileBytes);
                        }

                        UtilityServices.UploadBase64String(assetPath, $"{model.Id}_Right{Path.GetExtension(modelsModel.RightAngleImageBlob.FileName)}", uploadFile);
                        model.RightAngleImage = $"/Content/Models/{model.Id}/{model.Id}_Right{Path.GetExtension(modelsModel.RightAngleImageBlob.FileName)}";
                    }

                    _vwContext.Models.Update(model);
                    _vwContext.SaveChanges();

                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    modelsModel.ErrorMessage = ex.Message;
                }
            }

            return View(modelsModel);
        }

        public IActionResult Delete(int id)
        {
            var model = _vwContext.Models.Where(x => x.Id == id).FirstOrDefault();

            if (model != null)
            {
                model.IsDeleted = true;
                _vwContext.Models.Update(model);
                _vwContext.SaveChanges();
            }

            return RedirectToAction("Index");
        }
    }
}

VW.MSU.UI/Views/Models/CreateOrUpdate.cshtml
@model VW.MSU.Models.ModelsModel
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor httpContextAccessor
@{
    ViewData["Title"] = "Add/Edit Model";
}


<div class="create-card">
    <div class="create-wrp-header">
        <div class="create-record-title">
            <a asp-action="Index"> <span>&#8592; &nbsp;</span>@Html.Raw(Model.Id == 0 ? "Add" : "Edit") Model</a>
        </div>
    </div>
    <div class="create-form-main">
        <form id="CreateOrUpdateForm" asp-action="CreateOrUpdate" enctype="multipart/form-data" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @if (!string.IsNullOrEmpty(Model.ErrorMessage))
            {
                <div class="text-danger">@Model.ErrorMessage</div>
            }
            <input asp-for="Id" type="hidden" />
            <div class="form-group mb-form-sec">
                <div class="form-group-title">ADD Model Details</div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label asp-for="Name" class="control-label">Model Name</label>
                            <input asp-for="Name" class="form-control form-control-custom" placeholder="Model Name" />
                            <span asp-validation-for="Name" class="text-danger"></span>
                        </div>
                    </div>
                </div>
            </div>
            
            <div class="form-group mb-form-sec">
                <div class="form-group-title">ADD Model Image</div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <label class="control-label">Model Image</label>
                            <div class="custom-file">
                                <input asp-for="ImageBlob" class="custom-file-input form-control form-control-custom" />
                                <label asp-for="ImageBlob" class="control-label custom-file-label"></label>
                            </div>
                            <span asp-validation-for="ImageBlob" class="text-danger"></span>
                            @if (!string.IsNullOrEmpty(Model.Image))
                            {
                                <img src="@Url.Content(Model.Image)" style="width: 200px;" />
                            }
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="control-label">Front Angle Image</label>
                            <div class="custom-file">
                                <input asp-for="FrontAngleImageBlob" class="custom-file-input form-control form-control-custom" />
                                <label asp-for="FrontAngleImageBlob" class="control-label custom-file-label"></label>
                            </div>
                            <span asp-validation-for="FrontAngleImageBlob" class="text-danger"></span>
                            @if (!string.IsNullOrEmpty(Model.FrontAngleImage))
                            {
                                <img src="@Url.Content(Model.FrontAngleImage)" style="width: 200px;" />
                            }
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="control-label">Back Angle Image</label>
                            <div class="custom-file">
                                <input asp-for="BackAngleImageBlob" class="custom-file-input form-control form-control-custom" />
                                <label asp-for="BackAngleImageBlob" class="control-label custom-file-label"></label>
                            </div>
                            <span asp-validation-for="BackAngleImageBlob" class="text-danger"></span>
                            @if (!string.IsNullOrEmpty(Model.BackAngleImage))
                            {
                                <img src="@Url.Content(Model.BackAngleImage)" style="width: 200px;" />
                            }
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="control-label">Left Angle Image</label>
                            <div class="custom-file">
                                <input asp-for="LeftAngleImageBlob" class="custom-file-input form-control form-control-custom" />
                                <label asp-for="LeftAngleImageBlob" class="control-label custom-file-label"></label>
                            </div>
                            <span asp-validation-for="LeftAngleImageBlob" class="text-danger"></span>
                            @if (!string.IsNullOrEmpty(Model.LeftAngleImage))
                            {
                                <img src="@Url.Content(Model.LeftAngleImage)" style="width: 200px;" />
                            }
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="control-label">Right Angle Image</label>
                            <div class="custom-file">
                                <input asp-for="RightAngleImageBlob" class="custom-file-input form-control form-control-custom" />
                                <label asp-for="RightAngleImageBlob" class="control-label custom-file-label"></label>
                            </div>
                            <span asp-validation-for="RightAngleImageBlob" class="text-danger"></span>
                            @if (!string.IsNullOrEmpty(Model.RightAngleImage))
                            {
                                <img src="@Url.Content(Model.RightAngleImage)" style="width: 200px;" />
                            }
                        </div>
                    </div>
                </div>
            </div>
            
            <div class="form-group">
                <input type="submit" value="Submit" class="btn btn-medium btn-primary mr-2" />
                <a asp-action="Index" class="btn btn-medium btn-outline-primary mr-2">Back to List</a>
            </div>
        </form>

    </div>
</div>



@section header {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script type="text/javascript" src="~/js/RequiredIf.js"></script>
    <script type="text/javascript" src="~/js/AllowedExtensions.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $(".custom-file-input").on("change", function () {
                var fileName = $(this).val().split("\\").pop();
                $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
            });
        });
    </script>
}

VW.MSU.UI/Views/Models/Index.cshtml
@model IEnumerable<VW.MSU.Models.ModelsModel>
@{
    ViewData["Title"] = "Model List";
}
<div class="list-wrp-header">
    <div class="list-record-count">Models (@Model.Count())</div>
    <div class="list-filters">
        @*<a href="#" class="f-box f-box-calender">
            <img src="~/images/icons/calender-icon.svg" alt="calender" />
            <span>03 March, 2019</span>
        </a>*@
        <div class="f-box f-box-search">
            <input type="text" class="form-control form-control-custom" placeholder="Search">
            <button type="submit"><img src="~/images/icons/search-icon.svg" alt="search" /></button>
        </div>
        @*<a href="#" class="f-box f-box-xls">
            <img src="@Url.Content("~/images/icons/xls.png")" alt="XLS" />
            <span>XLS</span>
        </a>*@
        <a href="@Url.Action("CreateOrUpdate", "Models")" class="f-box f-box-btn">
            <span class="btn-icon btn-icon-add btn-icon-add-white"></span> Create Models
        </a>
    </div>
</div>
<div class="list-wrp-main scroller mCustomScrollbar">
    <div class="vw-tbl-list1">
        @if (Model.Count() > 0)
        {
            <div class="vw-row">
                <div class="vw-cell vw-cell-head"> @Html.DisplayNameFor(model => model.Name)</div>
                <div class="vw-cell vw-cell-head">&nbsp;</div>
            </div>
            foreach (var item in Model)
            {

                <div class="vw-row">
                    <div class="vw-cell">@item.Name</div>
                    <div class="vw-cell">
                        @Html.ActionLink("", "CreateOrUpdate", new { id = item.Id }, new { @class = "icon edit-icon" }) <span>|</span>
                        @Html.ActionLink("", "Delete", new { id = item.Id }, new { @class = "icon delete-icon" })
                    </div>
                </div>
            }
        }
        else
        {
            <div class="vw-row-no-data" style="text-align: center;background: #fff;padding: 25px;">
                <div class="vw-cell-no-data ">No data found.</div>
            </div>
        }
    </div>
</div>
@section Scripts{
    <script>
        (function ($) {
            $(window).on("load", function () {
                AutoHeight($(".scroller"), 10);
                $(".scroller").mCustomScrollbar({
                    theme: "minimal"
                });
            });
        })(jQuery);
    </script>
}