VW.MSU.UI/Controllers/DealershipController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using VW.MSU.Common;
using VW.MSU.Common.Enums;
using VW.MSU.Data.Models;
using VW.MSU.Models;
using VW.MSU.Services;
using VW.MSU.UI.Models;

namespace VW.MSU.UI.Controllers
{
    [Authorize]
    [SessionExpire]
    public class DealershipController : BaseController
    {
        public readonly ILogger<DealershipController> _logger;

        public DealershipController(IWebHostEnvironment hostingEnvironment, ILogger<DealershipController> logger, IConfiguration config, VWContext vwContext, IOptions<SFDCSettings> sfdcSettings)
            : base(hostingEnvironment, config, vwContext, sfdcSettings.Value)
        {
            _logger = logger;
        }

        #region Methods

        #endregion

        #region Create or Update Dealership

        public IActionResult CreateOrUpdate(long id = 0)
        {
            UserDetails userDetails = GetUserDetails();

            if ((userDetails.RoleId.HasValue && userDetails.RoleId.Value > 0) ||
                (userDetails.CMSRoleId.HasValue && (userDetails.CMSRoleId.Value == (int)CMSRoleTypes.VWADMIN || userDetails.CMSRoleId.Value == (int)CMSRoleTypes.SUPERADMIN || userDetails.CMSRoleId.Value == (int)CMSRoleTypes.GROUPDEALERADMIN)))
            {
                DealershipModel model;

                if (id > 0)
                {
                    var dealer = _vwContext.Dealership.Where(x => x.DealershipId == id).FirstOrDefault();
                    if (userDetails.CMSRoleId.HasValue && userDetails.CMSRoleId.Value == (int)CMSRoleTypes.GROUPDEALERADMIN)
                    {
                        if (dealer.GroupDealerId != userDetails.GroupDealerId)
                            return RedirectToAction("Index", "Home");
                    }

                    model = new DealershipModel
                    {
                        Address = dealer.Address,
                        AdminEmail = dealer.AdminEmail,
                        AdminFullName = dealer.AdminFullName,
                        AdminMobile = dealer.AdminMobile,
                        Code = dealer.Code,
                        DealershipId = dealer.DealershipId,
                        DealershipType = dealer.DealershipType,
                        Landline = dealer.Landline,
                        Location = dealer.Location,
                        Mobile = dealer.Mobile,
                        Stdcode = dealer.Stdcode,
                        GroupDealerId = dealer.GroupDealerId.HasValue ? dealer.GroupDealerId.Value : 0,
                        AreaManagerId = dealer.AreaManagerId.HasValue ? dealer.AreaManagerId.Value : 0,
                        Name = dealer.Name,
                        Image = dealer.Image,
                        AreaManagers = _vwContext.Users.Where(x => !x.IsDeleted && x.IsActive && x.RoleId == (int)RoleTypes.AREAMANAGER).Select(z => new SelectListItem { Text = z.Fullname, Value = z.UserId.ToString(), Selected = dealer.AreaManagerId.HasValue && dealer.AreaManagerId.Value == z.UserId }).ToList(),
                        GroupDealers = _vwContext.GroupDealer.Where(z => !z.IsDeleted && z.IsActive).Select(z => new SelectListItem { Text = z.Name, Value = z.GroupDealerId.ToString(), Selected = dealer.GroupDealerId == z.GroupDealerId }).ToList()
                    };
                }
                else
                {
                    model = new DealershipModel
                    {
                        AreaManagers = _vwContext.Users.Where(x => !x.IsDeleted && x.IsActive && x.RoleId == (int)RoleTypes.AREAMANAGER).Select(z => new SelectListItem { Text = z.Fullname, Value = z.UserId.ToString() }).ToList(),
                        GroupDealers = _vwContext.GroupDealer.Where(z => !z.IsDeleted && z.IsActive).Select(z => new SelectListItem { Text = z.Name, Value = z.GroupDealerId.ToString() }).ToList()
                    };
                }

                return View(model);
            }
            else
                return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public IActionResult CreateOrUpdate(DealershipModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    UserDetails userDetails = GetUserDetails();

                    var userId = int.Parse(HttpContext.User.Identity.Name ?? "-1");
                    var now = DateTime.Now;

                    Dealership dealer;
                    if (model.DealershipId > 0)
                    {
                        dealer = _vwContext.Dealership.Where(x => x.DealershipId == model.DealershipId).FirstOrDefault();
                    }
                    else
                    {
                        dealer = new Dealership
                        {
                            CreatedBy = userId,
                            CreatedDate = now,
                            IsDeleted = false,
                            IsActive = true
                        };
                    }

                    dealer.Name = model.Name;
                    dealer.Address = model.Address;
                    dealer.AdminEmail = model.AdminEmail;
                    dealer.AdminFullName = model.AdminFullName;
                    dealer.AdminMobile = model.AdminMobile;
                    dealer.Code = model.Code;
                    dealer.DealershipId = model.DealershipId;
                    dealer.DealershipType = model.DealershipType;
                    dealer.Landline = model.Landline;
                    dealer.Location = model.Location;
                    dealer.Mobile = model.Mobile;
                    dealer.Stdcode = model.Stdcode;

                    if (userDetails.CMSRoleId == (int)CMSRoleTypes.GROUPDEALERADMIN && userDetails.GroupDealerId > 0)
                        dealer.GroupDealerId = userDetails.GroupDealerId;
                    if (model.GroupDealerId > 0)
                        dealer.GroupDealerId = model.GroupDealerId;
                    else if (dealer.GroupDealerId > 0)
                        dealer.GroupDealerId = null;

                    if (model.AreaManagerId > 0)
                        dealer.AreaManagerId = model.AreaManagerId;

                    if (model.DealershipId > 0)
                        _vwContext.Dealership.Update(dealer);
                    else
                        _vwContext.Dealership.Add(dealer);

                    _vwContext.SaveChanges();

                    if (model.ImageBlob != null && model.ImageBlob.Length > 0)
                    {
                        var assetPath = $"{_hostingEnvironment.WebRootPath}/Content/Dealership/{dealer.DealershipId}";
                        var uploadFile = ConvertUploadFileToBase64String(model.ImageBlob);
                        UtilityServices.UploadBase64String(assetPath, $"{dealer.DealershipId}{Path.GetExtension(model.ImageBlob.FileName)}", uploadFile);
                        dealer.Image = $"/Content/Dealership/{dealer.DealershipId}/{dealer.DealershipId}{Path.GetExtension(model.ImageBlob.FileName)}";
                    }

                    _vwContext.Dealership.Update(dealer);
                    _vwContext.SaveChanges();

                    return RedirectToAction("List");
                }
                catch (Exception ex)
                {
                    model.ErrorMessage = ex.Message;
                }
            }

            model.AreaManagers = _vwContext.Users.Where(x => !x.IsDeleted && x.IsActive && x.RoleId == (int)RoleTypes.AREAMANAGER).Select(z => new SelectListItem { Text = z.Fullname, Value = z.UserId.ToString(), Selected = model.AreaManagerId == z.UserId }).ToList();
            model.GroupDealers = _vwContext.GroupDealer.Where(z => !z.IsDeleted && z.IsActive).Select(z => new SelectListItem { Text = z.Name, Value = z.GroupDealerId.ToString(), Selected = model.GroupDealerId == z.GroupDealerId }).ToList();

            return View(model);
        }

        #endregion

        public IActionResult List()
        {
            UserDetails userDetails = GetUserDetails();
            if ((userDetails.RoleId.HasValue && userDetails.RoleId.Value > 0) ||
                (userDetails.CMSRoleId.HasValue && (userDetails.CMSRoleId.Value == (int)CMSRoleTypes.VWADMIN || userDetails.CMSRoleId.Value == (int)CMSRoleTypes.SUPERADMIN || userDetails.CMSRoleId.Value == (int)CMSRoleTypes.GROUPDEALERADMIN)))
            {
                List<DealershipModel> model;
                if (userDetails.CMSRoleId.HasValue && userDetails.CMSRoleId.Value == (int)CMSRoleTypes.GROUPDEALERADMIN)
                {
                    model = _vwContext.Dealership.Where(x => x.GroupDealerId == userDetails.GroupDealerId && !x.IsDeleted).OrderByDescending(x => x.CreatedDate).Select(x => new DealershipModel()
                    {
                        DealershipId = x.DealershipId,
                        DealershipType = x.DealershipType,
                        Landline = x.Landline,
                        Mobile = x.Mobile,
                        AdminFullName = x.AdminFullName,
                        AdminEmail = x.AdminEmail,
                        AdminMobile = x.AdminMobile,
                        IsActive = x.IsActive,
                        Location = x.Location,
                        Code = x.Code,
                        Name = x.Name
                    }).ToList();
                }
                else
                {
                    model = _vwContext.Dealership.Where(x => !x.IsDeleted).OrderByDescending(x => x.CreatedDate).Select(x => new DealershipModel()
                    {

VW.MSU.UI/Views/Dealership/CreateOrUpdate.cshtml
@using Microsoft.AspNetCore.Http
@using VW.MSU.Common.Helpers
@using VW.MSU.Common.Enums
@model VW.MSU.Models.DealershipModel
@inject IHttpContextAccessor HttpContextAccessor
@{
    UserDetails userDetails = (UserDetails)SessionData.GetUserDetails(HttpContextAccessor.HttpContext);
    ViewData["Title"] = "Create";
}
@section styles {
    <link rel="stylesheet" href="~/css/jquery-datetimepicker.css" />
}


<div class="create-card">
    <div class="create-wrp-header">
        <div class="create-record-title">
            <a asp-action="List"> <span>&#8592; &nbsp;</span> @Html.Raw(Model.DealershipId > 0 ? "Update" : "Create") Dealership</a>
        </div>
    </div>
    <div class="create-form-main">
        <form>
            
        </form>
        <form id="CreateOrUpdateForm" asp-action="CreateOrUpdate" enctype="multipart/form-data" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @if (!string.IsNullOrEmpty(Model.ErrorMessage))
            {
                <div class="text-danger">@Model.ErrorMessage</div>
            }
            <input asp-for="DealershipId" type="hidden" />
            <div class="row">
                <div class="col-lg-6">
                    <div class="form-group">
                        <div class="form-group-title">BASIC INFORMATION</div>

                        <div class="form-row mb-4">
                            <div class="col-lg-12">
                                @*<label asp-for="Name" class="control-label"></label>*@
                                <input asp-for="Name" class="form-control form-control-custom" placeholder="Dealership Name"  />
                                <span asp-validation-for="Name" class="text-danger"></span>                                
                            </div>
                        </div>
                        <div class="form-row mb-4">
                            <div class="col-lg-6">                               
                                @*<label asp-for="Code" class="control-label"></label>*@
                                <input asp-for="Code" class="form-control form-control-custom" placeholder="Dealership Code" />
                                <span asp-validation-for="Code" class="text-danger"></span>
                            </div>
                            <div class="col-lg-6">                                
                                @*<label asp-for="Location" class="control-label"></label>*@
                                <input asp-for="Location" class="form-control form-control-custom" placeholder="Dealership Location" />
                                <span asp-validation-for="Location" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="form-row mb-4">
                            <div class="col-lg-12">                                
                                @*<label asp-for="Address" class="control-label"></label>*@
                                <input asp-for="Address" class="form-control form-control-custom" placeholder="Dealership Address" />
                                <span asp-validation-for="Address" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="form-row mb-4">
                            <div class="col-lg-6">
                                <div class="form-row">
                                    <div class="col contry-code">
                                        @*<label class="control-label">STD</label>*@
                                        @*<select class="std-selectJs form-control form-control-custom"
                                                name="std">
                                            <option value="00">00</option>
                                            <option value="00">000</option>
                                        </select>*@
                                        @*<label asp-for="Stdcode" class="control-label"></label>*@
                                        <input asp-for="Stdcode" class="form-control form-control-custom" placeholder="STD" type="number" maxlength="3" style="appearance: textfield; -webkit-appearance: textfield; -moz-appearance: textfield;"/>
                                        <span asp-validation-for="Stdcode" class="text-danger"></span>
                                    </div>
                                    <div class="col">                                      
                                        @*<label asp-for="Landline" class="control-label"></label>*@
                                        <input asp-for="Landline" class="form-control form-control-custom" placeholder="Landline Number"  />
                                        <span asp-validation-for="Landline" class="text-danger"></span>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-6">
                                @*<label asp-for="Mobile" class="control-label"></label>*@
                                <input asp-for="Mobile" class="form-control form-control-custom" placeholder="Mobile Number" />
                                <span asp-validation-for="Mobile" class="text-danger"></span>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="form-group-title">DEALERSHIP ADMIN</div>

                        <div class="form-row mb-4">
                            <div class="col-lg-6">                             
                                @*<label asp-for="AdminFullName" class="control-label"></label>*@
                                <input asp-for="AdminFullName" class="form-control form-control-custom" placeholder="Fullname" />
                                <span asp-validation-for="AdminFullName" class="text-danger"></span>
                            </div>
                            <div class="col-lg-6">
                                @*<label asp-for="AdminEmail" class="control-label"></label>*@
                                <input asp-for="AdminEmail" class="form-control form-control-custom" placeholder="Email" />
                                <span asp-validation-for="AdminEmail" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="form-row mb-4">
                            <div class="col-lg-6">
                                @*<label asp-for="AdminMobile" class="control-label"></label>*@
                                <input asp-for="AdminMobile" class="form-control form-control-custom" placeholder="Mobile Number" />
                                <span asp-validation-for="AdminMobile" class="text-danger"></span>
                            </div>
                        </div>
                    </div>
                    <div class="form-group mb-form-sec">
                        <div class="form-group-title">SELECT DEALERSHIP TYPE</div>
                        <div class="form-row">
                            <div class="col-12">
                                <div class="custom-control custom-radio custom-control-inline">
                                    <input type="radio" id="DealershipTypeInd" name="@Html.NameFor(m => m.DealershipType)" class="custom-control-input dealership-type" value="Individual" @Html.Raw(Model.DealershipType == "Individual" ? "checked='checked'" : "")>
                                    <label class="custom-control-label" for="DealershipTypeInd">Individual</label>
                                </div>
                                
                                <div class="custom-control custom-radio custom-control-inline">
                                    <input type="radio" id="DealershipTypeGrp" name="@Html.NameFor(m => m.DealershipType)" class="custom-control-input dealership-type" value="Group" @Html.Raw(Model.DealershipType == "Group" ? "checked='checked'" : "")>
                                    <label class="custom-control-label" for="DealershipTypeGrp">Group</label>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="form-group-title">SELECT AREA MANAGER</div>

                        <div class="form-row mb-4">
                            <div class="col-md-6">
                                <div class="form-group">
                                    @*<label asp-for="AreaManagerId" class="control-label"></label>*@
                                    <select class="areaManagerDDL areamanager-selectjs form-control form-control-custom" asp-for="AreaManagerId" asp-items="Model.AreaManagers">
                                        <option value="0">Select</option>
                                    </select>
                                    <span asp-validation-for="AreaManagerId" class="text-danger"></span>
                                </div>
                            </div>
                        </div>
                        @if (userDetails.CMSRoleId.HasValue && userDetails.CMSRoleId.Value != (int)CMSRoleTypes.GROUPDEALERADMIN)
                        {
                            <div class="form-row mb-4 grp-dealer" @Html.Raw((Model.DealershipType == "Group" || Model.GroupDealerId > 0) ? "" : "style='display: none'")>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        @*<label asp-for="GroupDealerId" class="control-label"></label>*@
                                        <select class="grpDealerDDL selectpicker form-control form-control-custom" asp-for="GroupDealerId" asp-items="Model.GroupDealers">
                                            <option value="0">Select</option>
                                        </select>
                                    </div>
                                </div>
                            </div>
                        }
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="form-group mb-4">
                        <div class="form-group-title">SHOWROOM IMAGE</div>
                        <div class="form-row">
                            <div class="col">                                
                                <div class="custom-file">
                                    <input asp-for="ImageBlob" class="custom-file-input form-control" style="display: none;" />
                                    <label asp-for="ImageBlob" class="control-label custom-file-label"></label>
                                </div>
                                <span asp-validation-for="ImageBlob" class="text-danger"></span>
                                @if (!string.IsNullOrEmpty(Model.Image))
                                {
                                    <img src="@Url.Content(Model.Image)" style="width: 200px;" />
                                }
                            </div>
                        </div>
                    </div>

                    @*<div class="form-group">
                        <div class="nsc-user">
                            <div class="form-group-title">NSC USER</div>
                            <div class="nsc-tbl">
                                <div class="nsc-cell">
                                    <div class="nsc-text-light">HO</div>
                                    <div class="nsc-text-dark">Kumar Singh</div>
                                </div>
                                <div class="nsc-cell">
                                    <div class="nsc-text-light">Zonal manager</div>
                                    <div class="nsc-text-dark">Amit trivedhi</div>
                                </div>
                                <div class="nsc-cell">
                                    <div class="nsc-text-light">area manager</div>
                                    <div class="nsc-text-dark">Bhavesh Patel</div>
                                </div>
                            </div>
                        </div>
                    </div>*@
                </div>
            </div>
            <div class="button-wrapper">
                <div class="left-btns">                  

                    <input type="submit" value="Submit" class="btn btn-medium btn-primary mr-2" />
                    <a asp-action="List" class="btn btn-medium btn-outline-primary mr-2">Cancel</a>
                </div>
                <div class="right-btns">
                    <button type="submit" class="btn btn-medium btn-outline-danger mr-2">
                        Delete Dealership
                    </button>
                </div>
            </div>

        </form>
    </div>
</div>


@section Scripts {
    <script src="~/js/Dealership/CreateOrUpdate.js"></script>
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script src="~/js/RequiredIf.js"></script>
    <script>
        $(document).ready(function () {
            $(".custom-file-input").on("change", function () {
                var fileName = $(this).val().split("\\").pop();
                $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
            });
        });
        $(".std-selectJs").select2({
            minimumResultsForSearch: -1,
            placeholder: "STD",
            allowClear: true,
        });
        $(".areamanager-selectjs ").select2({
            placeholder: "Select Area Manager",
            allowClear: true,
        });
    </script>
}

VW.MSU.UI/Views/Dealership/List.cshtml
@model IEnumerable<VW.MSU.Models.DealershipModel>
@{
    ViewData["Title"] = "List";
}
<div class="list-wrp-header">
    <div class="list-record-count">Dealership (@Model.Count())</div>
    <div class="list-filters">
        @*<a href="#" class="f-box f-box-calender">
            <img src="~/images/icons/calender-icon.svg" alt="calender" />
            <span>03 March, 2019</span>
        </a>*@
        <div class="f-box f-box-search">
            <input type="text" class="form-control form-control-custom" placeholder="Search">
            <button type="submit"><img src="~/images/icons/search-icon.svg" alt="search" /></button>
        </div>
        @*<a href="#" class="f-box f-box-xls">            
            <img src="@Url.Content("~/images/icons/xls.png")" alt="XLS" />
            <span>XLS</span>
        </a>*@
        <a href="@Url.Action("CreateOrUpdate", "Dealership")" class="f-box f-box-btn">
            <span class="btn-icon btn-icon-add btn-icon-add-white"></span>  Create Dealership
        </a>
    </div>
</div>
<div class="list-wrp-main scroller mCustomScrollbar">
    <div class="vw-tbl-list1">
        @if (Model.Count() > 0)
        {
            <div class="vw-row">
                <div class="vw-cell vw-cell-head"> Dealer Code</div>
                <div class="vw-cell vw-cell-head">Dealer</div>
                <div class="vw-cell vw-cell-head">Dealer Phone</div>
                <div class="vw-cell vw-cell-head">Dealer Admin</div>
                <div class="vw-cell vw-cell-head">Dealer Admin Phone</div>
                <div class="vw-cell vw-cell-head">Type</div>
                <div class="vw-cell vw-cell-head">Status</div>
                <div class="vw-cell vw-cell-head">Action</div>
            </div>
            foreach (var item in Model)
            {
                <div class="vw-row">
                    <div class="vw-cell">@item.Code</div>
                    <div class="vw-cell">
                        <div class="tbl-text-dark">@item.Name</div>
                        <div class="tbl-text-light">@item.Location</div>
                    </div>
                    <div class="vw-cell">@item.Mobile, @item.Stdcode-@item.Landline</div>
                    <div class="vw-cell">
                        <div class="tbl-text-dark">@item.AdminFullName</div>
                        <div class="tbl-text-light">@item.AdminEmail</div>
                    </div>
                    <div class="vw-cell">@item.AdminMobile</div>
                    <div class="vw-cell">@item.DealershipType</div>
                    <div class="vw-cell">@Html.Raw(item.IsActive ? "Active" : "Inactive")</div>

                    <div class="vw-cell">
                        @Html.ActionLink("", "CreateOrUpdate", new { id = item.DealershipId }, new { @class = "icon edit-icon" }) <span>|</span>
                        @Html.ActionLink("", "Delete", new { id = item.DealershipId }, new { @class = "icon delete-icon" })
                    </div>
                </div>
            }
        }
        else
        {
            <div class="vw-row-no-data" style="text-align: center;background: #fff;padding: 25px;">
                <div class="vw-cell-no-data ">No data found.</div>
            </div>
        }
    </div>
</div>
@section Scripts{
    <script>
        (function ($) {
            $(window).on("load", function () {
                AutoHeight($(".scroller"), 10);
                $(".scroller").mCustomScrollbar({
                    theme: "minimal"
                });

            });
        })(jQuery);
    </script>
}