VW.MSU.UI/Controllers/GroupDealerController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using System;
using System.Collections.Generic;
using System.Linq;
using VW.MSU.Common;
using VW.MSU.Common.Enums;
using VW.MSU.Data.Models;
using VW.MSU.Models;
using VW.MSU.UI.Models;

namespace VW.MSU.UI.Controllers
{
    [Authorize]
    [SessionExpire]
    public class GroupDealerController : BaseController
    {
        public readonly ILogger<GroupDealerController> _logger;

        public GroupDealerController(IWebHostEnvironment hostingEnvironment, ILogger<GroupDealerController> logger, IConfiguration config, VWContext vwContext, IOptions<SFDCSettings> sfdcSettings)
            : base(hostingEnvironment, config, vwContext, sfdcSettings.Value)
        {
            _logger = logger;
        }

        #region Methods

        #endregion

        #region Create or Update GroupDealer

        public IActionResult CreateOrUpdate(long id = 0)
        {
            UserDetails userDetails = GetUserDetails();

            if ((userDetails.RoleId.HasValue && userDetails.RoleId.Value > 0) ||
                (userDetails.CMSRoleId.HasValue && (userDetails.CMSRoleId.Value == (int)CMSRoleTypes.VWADMIN || userDetails.CMSRoleId.Value == (int)CMSRoleTypes.SUPERADMIN)))
            {
                GroupDealerModel model;
                if (id > 0)
                {
                    var grpDealer = _vwContext.GroupDealer.Where(x => x.GroupDealerId == id).FirstOrDefault();
                    model = new GroupDealerModel
                    {
                        GroupDealerId = grpDealer.GroupDealerId,
                        Name = grpDealer.Name,
                        GroupDealerUsers = grpDealer.GroupDealerUsers.Where(x => !x.IsDeleted).OrderBy(x => x.CreatedDate).Select(x => new GroupDealerUserModel() { Email = x.Email, Fullname = x.Fullname, Phone = x.Phone, Id = x.Id }).ToList()
                    };
                }
                else
                    model = new GroupDealerModel();

                return View(model);
            }
            else
                return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public IActionResult CreateOrUpdate(GroupDealerModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var userId = int.Parse(HttpContext.User.Identity.Name ?? "-1");
                    var now = DateTime.Now;

                    GroupDealer grpDealer;
                    if (model.GroupDealerId > 0)
                    {
                        grpDealer = _vwContext.GroupDealer.Where(x => x.GroupDealerId == model.GroupDealerId).FirstOrDefault();
                    }
                    else
                    {
                        grpDealer = new GroupDealer
                        {
                            CreatedBy = userId,
                            CreatedDate = now,
                            IsDeleted = false,
                            IsActive = true
                        };
                    }

                    grpDealer.Name = model.Name;

                    if (model.GroupDealerId > 0)
                        _vwContext.GroupDealer.Update(grpDealer);
                    else
                        _vwContext.GroupDealer.Add(grpDealer);

                    _vwContext.SaveChanges();

                    List<GroupDealerUsers> grpDealerUsers = new List<GroupDealerUsers>();
                    foreach (var grpDealerUser in model.GroupDealerUsers)
                    {
                        if (grpDealerUser.Id <= 0 && grpDealerUser.IsDeleted)
                        {

                        }
                        else
                        {
                            GroupDealerUsers groupDealerUser;
                            if (grpDealerUser.Id > 0)
                            {
                                groupDealerUser = _vwContext.GroupDealerUsers.Where(x => x.Id == grpDealerUser.Id).FirstOrDefault();
                            }
                            else
                            {
                                groupDealerUser = new GroupDealerUsers() { CreatedBy = userId, CreatedDate = DateTime.Now };
                            }

                            groupDealerUser.Email = grpDealerUser.Email;
                            groupDealerUser.Phone = grpDealerUser.Phone;
                            groupDealerUser.Fullname = grpDealerUser.Fullname;
                            groupDealerUser.GroupDealerId = grpDealer.GroupDealerId;
                            if (grpDealerUser.IsDeleted)
                            {
                                groupDealerUser.IsDeleted = true;
                            }

                            if (grpDealerUser.Id > 0)
                                _vwContext.GroupDealerUsers.Update(groupDealerUser);
                            else
                                grpDealerUsers.Add(groupDealerUser);
                        }
                    }

                    if (grpDealerUsers.Count() > 0)
                    {
                        _vwContext.GroupDealerUsers.AddRange(grpDealerUsers);
                    }

                    _vwContext.SaveChanges();

                    return RedirectToAction("List");
                }
                catch (Exception ex)
                {
                    model.ErrorMessage = ex.Message;
                }
            }

            return View(model);
        }

        #endregion

        public IActionResult List()
        {
            UserDetails userDetails = GetUserDetails();
            if ((userDetails.RoleId.HasValue && userDetails.RoleId.Value > 0) ||
                (userDetails.CMSRoleId.HasValue && (userDetails.CMSRoleId.Value == (int)CMSRoleTypes.VWADMIN || userDetails.CMSRoleId.Value == (int)CMSRoleTypes.SUPERADMIN)))
            {
                var model = _vwContext.GroupDealer.Where(x => !x.IsDeleted).OrderByDescending(x => x.CreatedDate).Select(x => new GroupDealerModel()
                {
                    Name = x.Name,
                    GroupDealerId = x.GroupDealerId,
                    IsActive = x.IsActive,
                    DealershipCount = x.Dealership.Where(y => !y.IsDeleted).Count()
                }).ToList();

                return View(model);
            }
            else
                return RedirectToAction("Index", "Home");
        }

        public IActionResult Delete(long id)
        {
            UserDetails userDetails = GetUserDetails();
            if ((userDetails.RoleId.HasValue && userDetails.RoleId.Value > 0) ||
            (userDetails.CMSRoleId.HasValue && (userDetails.CMSRoleId.Value == (int)CMSRoleTypes.VWADMIN || userDetails.CMSRoleId.Value == (int)CMSRoleTypes.SUPERADMIN)))
            {
                var grpDealer = _vwContext.GroupDealer.Where(x => x.GroupDealerId == id).FirstOrDefault();
                grpDealer.IsDeleted = true;
                _vwContext.GroupDealer.Update(grpDealer);
                _vwContext.SaveChanges();

                return RedirectToAction("List");
            }
            else
                return RedirectToAction("Index", "Home");
        }
    }
}

VW.MSU.UI/Controllers/SRController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using VW.MSU.Common;
using VW.MSU.Common.Enums;
using VW.MSU.Data.Models;
using VW.MSU.Models;
using VW.MSU.UI.Models;
using OfficeOpenXml;
using Microsoft.AspNetCore.Http;

namespace VW.MSU.UI.Controllers
{
    [Authorize]
    [SessionExpire]
    public class SRController : BaseController
    {
        public readonly ILogger<SRController> _logger;
        public readonly int PAGE_SIZE = 4;

        public SRController(IWebHostEnvironment hostingEnvironment, ILogger<SRController> logger, IConfiguration config, VWContext vwContext, IOptions<SFDCSettings> sfdcSettings)
            : base(hostingEnvironment, config, vwContext, sfdcSettings.Value)
        {
            _logger = logger;
        }

        #region Methods

        private static ServiceRequestModel GetServiceRequestModel(ServiceRequest serviceRequest)
        {
            return new ServiceRequestModel()
            {
                Srid = serviceRequest.Srid,
                CustomerName = serviceRequest.CustomerName,
                DealershipId = serviceRequest.DealershipId,
                Duration = serviceRequest.Duration,
                InvoiceAmount = serviceRequest.InvoiceAmount,
                Srnumber = serviceRequest.Srnumber,
                ServiceDateTime = serviceRequest.ServiceDateTime,
                VehicleModel = serviceRequest.VehicleModel,
                Vinnumber = serviceRequest.Vinnumber
            };
        }

        #endregion

        #region Create or Update User

        public IActionResult CreateOrUpdate(long id = 0)
        {
            UserDetails userDetails = GetUserDetails();

            if ((userDetails.RoleId.HasValue && userDetails.RoleId.Value > 0) ||
                (userDetails.CMSRoleId.HasValue && (userDetails.CMSRoleId.Value == (int)CMSRoleTypes.VWADMIN || userDetails.CMSRoleId.Value == (int)CMSRoleTypes.SUPERADMIN || userDetails.CMSRoleId.Value == (int)CMSRoleTypes.GROUPDEALERADMIN || userDetails.CMSRoleId.Value == (int)CMSRoleTypes.DEALERSHIPADMIN)))
            {
                ServiceRequestModel model;

                if (id > 0)
                {
                    var serviceRequest = _vwContext.ServiceRequest.Where(x => x.Srid == id).FirstOrDefault();
                    if (userDetails.CMSRoleId.HasValue && userDetails.CMSRoleId.Value == (int)CMSRoleTypes.GROUPDEALERADMIN)
                    {
                        var dealerships = _vwContext.Dealership.Where(x => x.GroupDealerId == userDetails.GroupDealerId && !x.IsDeleted).Select(x => x.DealershipId).ToList();
                        if (!dealerships.Contains(serviceRequest.DealershipId))
                            return RedirectToAction("Index", "Home");
                    }
                    else if (userDetails.CMSRoleId.HasValue && userDetails.CMSRoleId.Value == (int)CMSRoleTypes.DEALERSHIPADMIN)
                    {
                        if (serviceRequest.DealershipId != userDetails.DealershipId)
                            return RedirectToAction("Index", "Home");
                    }

                    model = new ServiceRequestModel
                    {
                        Srid = serviceRequest.Srid,
                        Srnumber = serviceRequest.Srnumber,
                        Vinnumber = serviceRequest.Vinnumber,
                        CustomerName = serviceRequest.CustomerName,
                        VehicleModelId = serviceRequest.VehicleModelId ?? 0,
                        //VehicleModel = serviceRequest.VehicleModel,
                        VariantName = serviceRequest.VariantName,
                        InvoiceAmount = serviceRequest.InvoiceAmount,
                        Duration = serviceRequest.Duration,
                        IsOilChange = serviceRequest.IsOilChange,
                        IsBrakes = serviceRequest.IsBrakes,
                        IsTyreCheck = serviceRequest.IsTyreCheck,
                        IsBatteryCheck = serviceRequest.IsBatteryCheck,
                        ServiceDate = serviceRequest.ServiceDateTime.ToString("dd/MM/yyyy hh:mm tt", CultureInfo.InvariantCulture),
                        DealershipId = serviceRequest.DealershipId,
                        CreatedDate = serviceRequest.CreatedDate,
                        RegNum = serviceRequest.RegNum,
                        Lat = serviceRequest.Lat,
                        Lng = serviceRequest.Lng,
                        OdometerReading = serviceRequest.OdometerReading,
                        ServiceType = serviceRequest.ServiceType
                    };

                    model.Models = _vwContext.Models.Where(x => !x.IsDeleted).Select(x => new SelectListItem { Text = x.Name, Value = x.Id.ToString(), Selected = serviceRequest.VehicleModelId.HasValue ? serviceRequest.VehicleModelId.Value == x.Id : false }).ToList();

                    if (serviceRequest.Dealership.GroupDealerId.HasValue)
                        model.GroupDealerId = serviceRequest.Dealership.GroupDealerId.Value;

                    if (userDetails.CMSRoleId.HasValue && userDetails.CMSRoleId.Value == (int)CMSRoleTypes.GROUPDEALERADMIN)
                    {
                        model.Dealerships = _vwContext.Dealership.Where(x => !x.IsDeleted && x.IsActive && x.GroupDealerId == userDetails.GroupDealerId).Select(x => new SelectListItem { Text = x.Name, Value = x.DealershipId.ToString(), Selected = serviceRequest.DealershipId == x.DealershipId }).ToList();
                    }
                    else if (userDetails.CMSRoleId.HasValue && userDetails.CMSRoleId.Value == (int)CMSRoleTypes.DEALERSHIPADMIN)
                    {
                        
                    }
                    else
                    {
                        if (model.GroupDealerId > 0)
                            model.Dealerships = _vwContext.Dealership.Where(x => !x.IsDeleted && x.IsActive && x.GroupDealerId == model.GroupDealerId).Select(x => new SelectListItem { Text = x.Name, Value = x.DealershipId.ToString(), Selected = serviceRequest.DealershipId == x.DealershipId }).ToList();
                        else
                            model.Dealerships = _vwContext.Dealership.Where(x => !x.IsDeleted && x.IsActive && !x.GroupDealerId.HasValue).Select(x => new SelectListItem { Text = x.Name, Value = x.DealershipId.ToString(), Selected = serviceRequest.DealershipId == x.DealershipId }).ToList();
                    }
                    model.ServiceAdvisers = _vwContext.Users.Where(x=>!x.IsDeleted).Select(x=> new SelectListItem { Text = x.Fullname, Value = x.UserId.ToString(), Selected = serviceRequest.Assignee.HasValue ? serviceRequest.Assignee.Value == x.UserId : false }).ToList();
                }
                else
                {
                    model = new ServiceRequestModel() { GroupDealerId = userDetails.GroupDealerId, DealershipId = userDetails.DealershipId };

                    model.Models = _vwContext.Models.Where(x => !x.IsDeleted).Select(x => new SelectListItem { Text = x.Name, Value = x.Id.ToString() }).ToList();

                    if (userDetails.CMSRoleId.HasValue && userDetails.CMSRoleId.Value == (int)CMSRoleTypes.GROUPDEALERADMIN)
                    {
                        model.Dealerships = _vwContext.Dealership.Where(x => !x.IsDeleted && x.IsActive && x.GroupDealerId == userDetails.GroupDealerId).Select(x => new SelectListItem { Text = x.Name, Value = x.DealershipId.ToString() }).ToList();
                    }
                    else if (userDetails.CMSRoleId.HasValue && userDetails.CMSRoleId.Value == (int)CMSRoleTypes.DEALERSHIPADMIN)
                    {
                    }
                    else
                    {
                        model.GroupDealers = userDetails.CMSRoleId.HasValue && userDetails.CMSRoleId.Value == (int)CMSRoleTypes.GROUPDEALERADMIN ? model.GroupDealers : _vwContext.GroupDealer.Where(z => !z.IsDeleted && z.IsActive).Select(z => new SelectListItem { Text = z.Name, Value = z.GroupDealerId.ToString() }).ToList();
                        model.Dealerships = _vwContext.Dealership.Where(x => !x.IsDeleted && x.IsActive && !x.GroupDealerId.HasValue).Select(x => new SelectListItem { Text = x.Name, Value = x.DealershipId.ToString() }).ToList();
                    }
                }

                ViewBag.GoogleMapAPIKey = GoogleMapAPIKey;
                return View(model);
            }
            else
                return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public IActionResult CreateOrUpdate(ServiceRequestModel model)
        {
            UserDetails userDetails = GetUserDetails();

            try
            {
                var userId = int.Parse(HttpContext.User.Identity.Name ?? "-1");
                var now = DateTime.Now;

                ServiceRequest serviceRequest;
                if (model.Srid > 0)
                {
                    serviceRequest = _vwContext.ServiceRequest.Where(x => x.Srid == model.Srid).FirstOrDefault();
                }
                else
                {
                    serviceRequest = new ServiceRequest
                    {
                        CreatedDate = now,
                        IsDeleted = false,
                        IsCompleted = false,
                        IsStarted = false
                    };
                }

                serviceRequest.Srnumber = model.Srnumber;
                serviceRequest.Vinnumber = model.Vinnumber;
                serviceRequest.CustomerName = model.CustomerName;
                //serviceRequest.VehicleModel = model.VehicleModel;

VW.MSU.UI/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@using VW.MSU.Common.Enums
@inject IHttpContextAccessor HttpContextAccessor
@{
    UserDetails userDetails = (UserDetails)SessionData.GetUserDetails(HttpContextAccessor.HttpContext);
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Volkswagen MSU</title>
    <link href="~/lib/bootstrap/css/bootstrap.css" rel="stylesheet" />
    <link href="~/lib/customscroller/jquery.mCustomScrollbar.css" rel="stylesheet" />

    
    <link href="~/fonts/fonts.css" rel="stylesheet" />
    <link href="~/js/plugins/selectjs/select2.min.css" rel="stylesheet" />
    <link href="~/css/style.css" rel="stylesheet" />

    @RenderSection("styles", required: false) 
    @RenderSection("header", required: false)
</head>
<body class="body_bg">
    <div class="admin-wrapper">
        <header>
            <div class="container" style="height:100%">
                <div class="header-inner">
                    <a href="#" class="hamburger">
                        <img src="@Url.Content("~/images/icons/menu-icon.svg")" alt="menu" /> Menu
                    </a>
                    <div class="navWrapper" style="display: none">
                        <div class="navWrapper-inner">
                            <div class="close-menu">
                                <img src="@Url.Content("~/images/icons/close-icon.svg")" alt="close" /> Close
                                Menu
                            </div>
                            <nav>
                                @if ((userDetails.RoleId.HasValue && userDetails.RoleId.Value > 0) ||
(userDetails.CMSRoleId.HasValue && (userDetails.CMSRoleId.Value == (int)CMSRoleTypes.VWADMIN || userDetails.CMSRoleId.Value == (int)CMSRoleTypes.SUPERADMIN)))
                                {
                                    <ul class="navbar-nav mr-auto">
                                        <li class="nav-item">
                                            <a class="nav-link" asp-controller="GroupDealer" asp-action="List">
                                                Manage Group Dealers
                                                <div class="icon-wrp">
                                                    <img src="~/images/icons/right-caret-icon.png"
                                                         alt="right icon" />
                                                </div>
                                            </a>
                                        </li>
                                    </ul>
                                    <ul class="navbar-nav mr-auto">
                                        <li class="nav-item">
                                            <a class="nav-link" asp-controller="Models" asp-action="Index">
                                                Manage Models
                                                <div class="icon-wrp">
                                                    <img src="~/images/icons/right-caret-icon.png"
                                                         alt="right icon" />
                                                </div>
                                            </a>
                                        </li>
                                    </ul>
                                }
                                @if ((userDetails.RoleId.HasValue && userDetails.RoleId.Value > 0) ||
(userDetails.CMSRoleId.HasValue && (userDetails.CMSRoleId.Value == (int)CMSRoleTypes.VWADMIN || userDetails.CMSRoleId.Value == (int)CMSRoleTypes.SUPERADMIN || userDetails.CMSRoleId.Value == (int)CMSRoleTypes.GROUPDEALERADMIN)))
                                {
                                    <ul class="navbar-nav mr-auto">
                                        <li class="nav-item">
                                            <a class="nav-link" asp-controller="Dealership" asp-action="List">
                                                Manage Dealerships
                                                <div class="icon-wrp">
                                                    <img src="~/images/icons/right-caret-icon.png"
                                                         alt="right icon" />
                                                </div>
                                            </a>
                                        </li>
                                    </ul>
                                }
                                @if ((userDetails.RoleId.HasValue && userDetails.RoleId.Value > 0) ||
(userDetails.CMSRoleId.HasValue && (userDetails.CMSRoleId.Value == (int)CMSRoleTypes.VWADMIN || userDetails.CMSRoleId.Value == (int)CMSRoleTypes.SUPERADMIN || userDetails.CMSRoleId.Value == (int)CMSRoleTypes.GROUPDEALERADMIN || userDetails.CMSRoleId.Value == (int)CMSRoleTypes.DEALERSHIPADMIN)))
                                {
                            <ul class="navbar-nav mr-auto">
                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="User" asp-action="List">
                                        Manage Users
                                        <div class="icon-wrp">
                                            <img src="~/images/icons/right-caret-icon.png"
                                                 alt="right icon" />
                                        </div>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="SR" asp-action="List">
                                        Manage Service Requests
                                        <div class="icon-wrp">
                                            <img src="~/images/icons/right-caret-icon.png"
                                                 alt="right icon" />
                                        </div>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="ServiceAdvisor" asp-action="List">
                                        Manage Service Adviser Requests
                                        <div class="icon-wrp">
                                            <img src="~/images/icons/right-caret-icon.png"
                                                 alt="right icon" />
                                        </div>
                                    </a>
                                </li>
                            </ul>
                                }

                            </nav>
                            <div class="profile-nav">
                                @if (!string.IsNullOrEmpty(userDetails.Fullname))
                                {

                                    <div class="pn-col">
                                        <img src="~/images/icons/avatar-sample.png" alt="avatar" class="img-fluid" />
                                    </div>
                                    <div class="pn-col">
                                        <div class="pn-name">Welcome @userDetails.Fullname</div>
                                        <div class="pn-role">Super Admin</div>
                                        <div class="pn-role"><a href="@Url.Action("Logout", "Home")">Logout</a></div>
                                    </div>

                                }

                            </div>
                        </div>
                    </div>                  
                </div>
                <span class="logo-row">
                    <span class="logo-image">
                        <img src="@Url.Content("~/images/icons/logo.svg")" alt="logo" />
                    </span>
                </span>
            </div>
        </header>
        <div class="container">
            <main role="main" class="">
                @RenderBody()
            </main>
        </div>
    </div>
    <script src="~/js/jquery-3.6.0.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.bundle.js"></script>
    <script src="~/lib/customscroller/jquery.mCustomScrollbar.concat.min.js"></script>
    <script src="~/js/plugins/selectjs/select2.min.js"></script>
    <script src="~/js/autoHeight.js"></script>
    <script src="https://cdn.amcharts.com/lib/4/core.js"></script>
    <script src="https://cdn.amcharts.com/lib/4/charts.js"></script>
    <script src="https://cdn.amcharts.com/lib/4/themes/animated.js"></script>
    <script src="~/js/Common.js"></script>

    <script>
        var baseUrl = "@Url.Content("~/")";
    </script>
    @RenderSection("Scripts", required: false)
</body>
</html>

VW.MSU.UI/Views/Shared/_LoginLayout.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor
@{

}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>@ViewData["Title"]</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />

    <!-- Bootstrap core CSS -->
    <link href="~/fonts/fonts.css" rel="stylesheet" />
    <link href="~/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/vendor/select2/select2.min.css" rel="stylesheet" />
    <link href="~/vendor/custom_scrollbar/jquery.mCustomScrollbar.min.css" rel="stylesheet" />
    <link href="~/css/style.css" rel="stylesheet" />
    @RenderSection("Styles", required: false)
    <script src="~/vendor/jquery/jquery.js"></script>
</head>
<body>
    @RenderBody()
    @RenderSection("RenderFooter", required: false)
    <script src="~/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/vendor/custom_scrollbar/jquery.mCustomScrollbar.concat.min.js"></script>
    <script src="~/vendor/stickybits/stickybits.min.js"></script>
    <script src="~/vendor/select2/select2.full.js"></script>
    <script>
        var baseUrl = "@Url.Content("~/")";
    </script>
    @RenderSection("Scripts", required: false)
</body>
</html>